#!/usr/bin/env bash
# Rewrite ios/Mewmew/BuildConfig.swift with the token from MEWMEW_APP_TOKEN.
#
# Run before `xcodegen generate` in CI. Without a token the file keeps its empty
# default and the app simply never calls the parse worker.

set -euo pipefail

target="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/ios/Mewmew/BuildConfig.swift"
token="${MEWMEW_APP_TOKEN:-}"

if [ -z "$token" ]; then
  echo "MEWMEW_APP_TOKEN is empty; leaving BuildConfig.swift untouched" >&2
  exit 0
fi

case "$token" in
  *[!0-9A-Za-z_-]*)
    echo "error: MEWMEW_APP_TOKEN has characters outside [0-9A-Za-z_-]" >&2
    exit 1
    ;;
esac

cat > "$target" <<EOF
/// Build-time configuration. Generated by scripts/inject-app-token.sh —
/// do not edit or commit the value below.
enum BuildConfig {
    static let appToken = "$token"
}
EOF

echo "injected app token into $target (${#token} chars)"
